//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulado_Remote_Administration.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategorias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subcategorias()
        {
            this.Questoes = new HashSet<Questoes>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Pai { get; set; }
        public int Qtd { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questoes> Questoes { get; set; }
    }
}
