//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulados.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questao()
        {
            this.Alternativas = new HashSet<Alternativa>();
            this.Simulados_Questoes = new HashSet<Simulados_Questoes>();
        }
    
        public int Id { get; set; }
        public string Enunciado { get; set; }
        public string Imagem { get; set; }
        public int Correta { get; set; }
        public int Cat { get; set; }
    
        public virtual Subcategoria Subcategorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alternativa> Alternativas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Simulados_Questoes> Simulados_Questoes { get; set; }
    }
}
