//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulados.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Simulado()
        {
            this.Questoes = new HashSet<Simulados_Questoes>();
        }
    
        public int Id { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Data { get; set; }
        public int Cat { get; set; }
    
        public virtual Categoria Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Simulados_Questoes> Questoes { get; set; }
        public virtual Usuario Usuarios { get; set; }
    }
}
