//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulados.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulados_Questoes
    {
        public int Simulado { get; set; }
        public int Questao { get; set; }
        public Nullable<int> Marcada { get; set; }
    
        public virtual Simulado Simulados { get; set; }
        public virtual Questao Questoes { get; set; }
    }
}
